# render.yaml for FinVestify deployment

services:
  - name: finvestify-client
    type: web
    env: static
    branch: master
    staticPublishPath: client/dist  # assuming build in dist
    buildCommand: npm install && npm run build
    plan: free

  - name: finvestify-node-server
    type: web
    env: node
    branch: master
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
  - key: MONGO_URI
    value: "${MONGO_URI}"
  - key: JWT_SECRET_KEY
    value: "${JWT_SECRET_KEY}"
  - key: FINHUB_API_KEY
    value: "${FINHUB_API_KEY}"
  - key: NEWS_API_KEY
    value: "${NEWS_API_KEY}"
  - key: GEMINAI_API_KEY
    value: "${GEMINAI_API_KEY}"
  - key: GEMINAI_BASE_URL
    value: "${GEMINAI_BASE_URL}"
  - key: TWELVE_DATA_API_KEY
    value: "${TWELVE_DATA_API_KEY}"

      # ... כל משתני סביבה נדרשים

  - name: finvestify-python-backend
    type: web
    env: python
    branch: master
    buildCommand: cd server/python-backend && pip install -r requirements.txt
    startCommand: cd server/python-backend && python stock_data.py
    plan: free
    envVars:
      - key: TWELVE_DATA_API_KEY
        value: "${TWELVE_DATA_API_KEY}"

      # ... עוד במידת הצורך

  - name: finvestify-python-predict
    type: web
    env: python
    branch: master
    buildCommand: cd server/python-backend && pip install -r requirements.txt
    startCommand: cd server/python-backend && python predict_stock.py
    plan: free
    envVars:
      - key: TWELVE_DATA_API_KEY
        value: "${TWELVE_DATA_API_KEY}"

